#!/usr/bin/env bash
printf "starting integration tests"
NODE_ENV=LOCAL node_modules/mocha/bin/_mocha --require ts-node/register -u bdd --timeout 999999 --colors --recursive --exit test/integration/**/*.ts
printf "finished integration tests"
